# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160515_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='post',
        ),
    ]
