# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_resource_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='post',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='blog.Post'),
            preserve_default=False,
        ),
    ]
