# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_resource_movie_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='post',
        ),
    ]
