# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_resource_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='external_url',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
