# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160517_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='small_image',
            field=models.ImageField(null=True, upload_to='image/profile/%Y/%m/%d'),
        ),
    ]
