# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160614_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='small_image',
            field=models.ImageField(blank=True, default=True, upload_to='image/profile/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
