# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20160616_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Username may contain only letters, numbers and @.+-_ characters.'}, help_text='Required. 30 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username jebal.', 'invalid')], verbose_name='username'),
        ),
    ]
